name: Build Repairis ISO with Nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure Cachix
        uses: cachix/cachix-action@v14
        with:
          name: repairis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build ISO and Push to Cachix
        run: nix build path:$PWD | cachix push repairis

      - name: Find and Rename ISO file
        id: find_iso
        run: |
          SHORT_COMMIT=$(echo "${GITHUB_SHA::7}")
          ORIGINAL_ISO_PATH=$(find ./result/iso -name "*.iso" -print -quit)
          NEW_ISO_FILENAME="Repairis-${SHORT_COMMIT}.iso"
          TEMP_ISO_DIR="./temp-iso-output"
          FINAL_ISO_PATH="$TEMP_ISO_DIR/$NEW_ISO_FILENAME"

          if [ -z "$ORIGINAL_ISO_PATH" ]; then
            echo "Error: ISO file not found in ./result/iso"
            exit 1
          fi

          mkdir -p "$TEMP_ISO_DIR"
          cp "$ORIGINAL_ISO_PATH" "$FINAL_ISO_PATH"
          echo "Copied and renamed ISO to $FINAL_ISO_PATH"
          echo "iso_path=$FINAL_ISO_PATH" >> "$GITHUB_OUTPUT"
          echo "short_commit=$SHORT_COMMIT" >> "$GITHUB_OUTPUT"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: Repairis-${{ steps.find_iso.outputs.short_commit }}
          path: ${{ steps.find_iso.outputs.iso_path }}
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.find_iso.outputs.short_commit }}
          name: Repairis Release ${{ steps.find_iso.outputs.short_commit }}
          files: ${{ steps.find_iso.outputs.iso_path }}
